[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
cinnog.workspace = true

leptos.workspace = true
leptos_meta.workspace = true
tracing.workspace = true
bevy_ecs.workspace = true
serde.workspace = true
leptos-use = "0.15.7"

leptos_router = { workspace = true, features = ["nightly"] }
cinnog_mod_markdown = { path = "../crates/cinnog_mod_markdown" }

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]
